steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/excelmec/excel-merch-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/excelmec/excel-merch-backend:latest'
      - '-f'
      - 'Dockerfile.cron'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/github.com/excelmec/excel-merch-backend:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/github.com/excelmec/excel-merch-backend:latest'
